---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshotter-crd
spec:
  project: infrastructure

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    path: client/config/crd
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v7.0.2

  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-snapshotter
spec:
  project: infrastructure

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    path: deploy/kubernetes/snapshot-controller
    repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
    targetRevision: v7.0.2

  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: infrastructure

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.1
    helm:
      valuesObject:
        defaultSettings:
          storageReservedPercentageForDefaultDisk: 1
          defaultReplicaCount: 2
          defaultDataLocality: best-effort

        persistence:
          defaultClassReplicaCount: 2
          defaultDataLocality: best-effort

        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
