---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v7.0.2/client/config/crd/kustomization.yaml
- https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/refs/tags/v7.0.2/deploy/kubernetes/snapshot-controller/kustomization.yaml
- volumesnapshotclass.yaml
