kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-backup-vsc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: bak
