---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app.yaml

patches:
- target:
    group: deviceplugin.intel.com
    version: v1
    kind: GpuDevicePlugin
    name: igpu
  patch: |-
    - op: remove
      path: /spec/resourceManager
