---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: infrastructure

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: oauth2-proxy
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 8.2.1

  destination:
    server: "https://kubernetes.default.svc"
    namespace: oauth2-proxy
