---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            nodeSelector:
              kubernetes.io/arch: arm64
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - name: vm01.vfd.ovh
              path:
              - /
              port: http
            tls:
            - secretName: vm01-vfd-tls
              hosts:
              - vm01.vfd.ovh
          persistentVolume:
            name: victoria-metrics-01-data
            size: 100Gi
            storageClassName: longhorn
            accessModes:
            - ReadWriteOnce
  destination:
    server: "https://kubernetes.default.svc"
    namespace: victoria-metrics-arm
