---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-01
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - name: vm01.vfd.ovh
              path:
              - /
              port: http
            tls:
            - secretName: vm01-vfd-tls
              hosts:
              - vm01.vfd.ovh
          persistentVolume:
            name: victoria-metrics-01-data
            size: 100Gi
            storageClassName: longhorn
            accessModes:
            - ReadWriteOnce
