apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-multimedia
provisioner: smb.csi.k8s.io
parameters:
  source: //nas.vfd.ovh/Multimedia
  csi.storage.k8s.io/node-stage-secret-name: smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: csi-driver-smb
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
- dir_mode=0777
- file_mode=0777
- uid=1001
- gid=1001
