---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        server:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - name: vm.vfd.ovh
              path:
              - /api
            - name: vmui.vfd.ovh
              path:
              - /vmui
            tls:
            - secretName: victoria-metrics-vfd-tls
              hosts:
              - vmui.vfd.ovh
              - vm.vfd.ovh
          persistentVolume:
            name: victoria-metrics-data
            size: 50Gi
            storageClassName: longhorn
            accessModes:
            - ReadWriteOnce
