---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        k8sServiceHost: 192.168.10.205
        k8sServicePort: 6443
        routingMode: native
        kubeProxyReplacement: true
        cni:
          exclusive: false
        k8sClientRateLimit:
          qps: 50
          burst: 100
        bpf:
          autoMount:
            enabled: false
        socketLB:
          hostNamespaceOnly: true
        l2announcements:
          enabled: true
        externalIPs:
          enabled: true
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
            - 100.64.0.0/16
