---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: babybuddy
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.3.0
    helm:
      valuesObject:
        controllers:
          main:
            containers:
              main:
                image:
                  repository: lscr.io/linuxserver/babybuddy
                  tag: 2.7.1
                  pullPolicy: IfNotPresent

                env:
                  TZ: "Europe/Paris"
                  PUID: 1000
                  PGID: 1000
                  ALLOWED_HOSTS: "babybuddy.vfd.ovh"
                  CSRF_TRUSTED_ORIGINS: "http://babybuddy.vfd.ovh,https://babybuddy.vfd.ovh"
                  CSRF_COOKIE_SECURE: true
                  SECURE_PROXY_SSL_HEADER: true
                  SESSION_COOKIE_SECURE: true
                  REVERSE_PROXY_AUTH: true
                  PROXY_HEADER: "HTTP_X_AUTH_REQUEST_PREFERRED_USERNAME"
                  DEBUG: true
                  
        service:
          main:
            controller: main
            ports:
              http:
                primary: true
                port: 8000

        ingress:
          main:
            enabled: true
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
              nginx.ingress.kubernetes.io/auth-signin: "https://oidc.vfd.ovh/oauth2/start?rd=$scheme://$host"
              nginx.ingress.kubernetes.io/auth-url: "https://oidc.vfd.ovh/oauth2/auth?allowed_groups=babybuddy_users"
              nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-Preferred-Username"
            hosts:
              - host: "babybuddy.vfd.ovh"
                paths:
                  - path: /
                    pathType: Prefix
                    service:
                      identifier: main
                      port: http
            tls:
              - secretName: babybuddy-vfd-tls
                hosts:
                  - "babybuddy.vfd.ovh"

        persistence:
          config:
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            size: 1Gi
            globalMounts:
              - path: /config
            storageClass: "longhorn"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: babybuddy