---
apiVersion: v1
kind: Namespace
metadata:
  name: emqx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls
  namespace: emqx
spec:
  dnsNames:
  - mqtt.vfd.ovh
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prd
  secretName: mqtt-tls
  usages:
  - digital signature
  - key encipherment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-acls
  namespace: emqx
data:
  acl.conf: |
    {allow, {username, {re, "^dashboard$"}}, subscribe, ["$SYS/#"]}.
    {allow, {ipaddr, "127.0.0.1"}, all, ["$SYS/#", "#"]}.
    {allow, {username, "zigbee2mqtt"}, all, ["zigbee2mqtt/#", "homeassistant/#", "hass/status"]}.
    {allow, {username, "home-assistant"}, all, ["zigbee2mqtt/#", "homeassistant/#", "hass/status", "drop_connect/discovery/#"]}.
    {deny, all, subscribe, ["$SYS/#", {eq, "#"}, {eq, "+/#"}]}.
    {deny, all}.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: emqx-dashboard
  namespace: emqx
spec:
  encryptedData:
    EMQX_DASHBOARD__DEFAULT_PASSWORD: AgAk9gHTXFqfvBWUyA8zM33CTFdA8feilDyFulj8RV6IrtU5R0CLyVQGLNfLO0cP9HdL6tZc60CGn3q/WsUHd8DfEgtST5MFG/EuJ627ygEKO3NbshpMjaXP17UOqk6kWRnB9kcAEfx699RoPRA2ZDDOgW+5O6HRO6g6+GbVHgJhf+OpL+6IR6Jvl0u2vtxlR2agak6spYlboZSGeaT9gjTpl7SxMePsKFih55/pXuYm0miZEcfp2K8i8ucb+sOb4++JHbWFqORLtgcajPJzzjfchIouu9dT5yZiAefKhma9fV3DbbMFcZQyaAFCwjQkcZRldzInAXx5bfDNgNtyJj1k2JT0QhOWf1E9pqYM95ayWl5mf1tDNfMdiKq+5JuT+D0otoB06AZuZ9ZXAilxKL6zdAcyYjDcc4yc0VK7YjTqJb/j8fqHMCFPtYnH7Iym1uMqUDFC0j+zlesSGlWKTD05JPZzhg/KZJerf+6nW981xFNiz7KN89sfwCDXiG8FUl6nzYIuWSfboP/B0OlCxMiEwMwlgv+RUisBDqX2ky7QjkTfALZpHy9PtEbiWYR0s2smfruhH5MzIVlAUG/xC1jSa/T+ENIV0GWqVEKAz/0GEU77sPRqvhSR5UFg2APvF9j5C07M/3P1SWK4cAyI8iwkzM01nJESMzvIZV8u2+GaEG2FiKi7/UoRrjDVuWtjeC1h8Wg8JBNJOXclh7TW6LtKLtM5HR2V9TE=
    EMQX_DASHBOARD__DEFAULT_USERNAME: AgBWf89jRZzcHXo5x/i1ZCNvL/vWy81Gl5+6vBpa1bpBnYhiZqY+L4CXTPSp4rhCLSw1tnz1H/8ZNl2wXijFPd7pud80bdnaOuPM+/lxmqLBVUmh2O2YEKPSDoCrGIaE6WPgKDjNAreJC5SfnlBOFh7ACOhFbvx/fA0lEpY2jVzfFcVhkLwoS0ueaeNoOchWX0TDfBmZcQIsTbvAXdcq9v6gr9YWXhQElAJpMK/KmV4dU+70L5wXDuiDTJlpz9kkUu5pIVeGwTf8OG7TaMPbuqE9V/RtCV6wtuRy3axBbBtEeW6oR41BqSlJTSpZkhYc7Zorm6tfkTedjnkRsB08zQNuZSlGZky9exsLC/T2092yRhIC61smJdZGdQ1fUPoePamEYtJLLVV91lIgzwNAcrRSOoeuwHgT2vyg9NnmxdHNfv3/YdsOKjNHf/n+Wi9b4dlCL8KCA36QoXVsYTv/nPIMijmXnDJMRuh2uOg25n8ViW6KGYV2dbSh1MAqiLLPua809OwHoCrkfJvdHKr150YNA1uEE2ncywW8QOpLU1Y+FcMKynJ/7WgKOim9v5a2J8CFnyZg4I1ohqgfqvyN6BR+cdn1FCGuYHzr+Bl8FrSjyQLamO8EkKtQ1VcBj2R7rvfJOk3sxeKzK0NC38HX2hb7zUN2YRUIKHA6dR/1RevKydTxczQyktXX7QPLLiPuaUImxOM3Qw==
  template:
    metadata:
      name: emqx-dashboard
      namespace: emqx
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: emqx-users
  namespace: emqx
spec:
  encryptedData:
    users.csv: AgATNmK373xkFrS9h/aI8zDMaGStubXCFudj0pzRqhtGgRZoNEGuhYh32kTnySqW1s+il4P0AKoVSQVgcp63go5OYNJUji87jc4Cuj1KjY2XJ5UZ3m+YqyVL4snxeP/LJpGPHgUn5SBgnpuuukXYvQQyW7COkG/qw0BOcctc/BTA55m5DNhDfk80D/fMar3U+rRlKWtt9TI2WTF9OL8FF/tQ/cwjDu0Z7e8ckhvh1mVmfUzZ/Dow4kkB2rfqizRI5ANBCNNnQf7GDK3F2rQNwfxfeFiHmwMlJiRNMsMNOK9M/+uHUyIY6iBpAjcJ7gQbQ9nHwHQS4vcFlp06hjH8zABDFZk7MWt8JwkQtSn1jfH1hEPmbko8i4MY40r0Zhva74nVcrqBl/qKTNfbpCj5nawm6waQLcaW6xbv3H9bCND1ooGDBkDtcwNoAJvbrpu3y4c/raJQ4C/2NMywgnlwEnhEaK4hrswO4rAjCtvDvSHfuP4BgOeBabHdzyZNZ1cag7CH52eCKnQEqwsYBOlKkwrtrTrKgjrtpuFENyyuj6WW895XqLvoxYL/xbroq36M5PRzgGJYRifPbt6MEqi2jZmnOx6AY8TOI6CEdj45J5Cw9TYRp4/t2mM+MJOYcVCcdIOS/3DzJWWyUiionegATyo1wEftm+tzzw+nlF8OykzJxbTpD/5pDJN2StbWCXvsYDtdiUETM6De+hzpLSisKo8W/OjINYwQP8MCqSfUEJwTHPIBxtV0qBY3j0N5NYmst1ArxCbQ8gj2ye7KQq3c3TdGLi7mZ2cy4FwPzyRaBOAWmBrP2CehPLDv9z+KPEdqjLxTnXRNzh84ORD37Z45y34j
  template:
    metadata:
      name: emqx-users
      namespace: emqx
    type: Opaque
---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  image: emqx:5.8.3
  config:
    data: |
      authentication = [
        {
          backend = built_in_database
          mechanism = password_based
          password_hash_algorithm {name = sha256, salt_position = suffix}
          user_id_type = username
          
          bootstrap_file = "/mounted/users/users.csv"
          bootstrap_type = plain
        }
      ]

      authorization {
        deny_action = ignore
        no_match = deny
        sources = [
          {
            type = file
            enable = true
            path = "/mounted/acls/acl.conf"
          }
        ]
      }

      listeners.tcp.default.enable = false
      listeners.ws.default.enable = false

      listeners.wss.default {
        bind = "0.0.0.0:8084"
        websocket.mqtt_path = "/mqtt"
        ssl_options {
          certfile = "/mounted/cert/tls.crt"
          keyfile = "/mounted/cert/tls.key"
        }      
      }

      listeners.ssl.default {
        bind = "0.0.0.0:8883"
        ssl_options {
          certfile = "/mounted/cert/tls.crt"
          keyfile = "/mounted/cert/tls.key"
          gc_after_handshake = true
          handshake_timeout = 5s
        }
      }
  coreTemplate:
    spec:
      replicas: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: apps.emqx.io/instance
                operator: In
                values:
                - emqx
            topologyKey: kubernetes.io/hostname
      envFrom:
      - secretRef:
          name: emqx-dashboard
      volumeClaimTemplates:
        storageClassName: longhorn-local
        resources:
          requests:
            storage: 5Gi
        accessModes:
        - ReadWriteOnce
      extraVolumes:
      - name: mqtt-tls
        secret:
          secretName: mqtt-tls
      - name: accounts
        secret:
          secretName: emqx-users
      - name: acls
        configMap:
          name: emqx-acls
      extraVolumeMounts:
      - name: mqtt-tls
        mountPath: /mounted/cert
      - name: accounts
        mountPath: /mounted/users
      - name: acls
        mountPath: /mounted/acls
  dashboardServiceTemplate:
    spec:
      type: ClusterIP
  listenersServiceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.vfd.ovh
    spec:
      type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-dashboard
  namespace: emqx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
spec:
  ingressClassName: nginx
  rules:
  - host: emqx.vfd.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emqx-dashboard
            port:
              number: 18083
  tls:
  - hosts:
    - emqx.vfd.ovh
    secretName: emqx-vfd-tls
