---
apiVersion: v1
kind: Namespace
metadata:
  name: emqx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mqtt-tls
  namespace: emqx
spec:
  dnsNames:
  - mqtt.vfd.ovh
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prd
  secretName: mqtt-tls
  usages:
  - digital signature
  - key encipherment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-acls
  namespace: emqx
data:
  acl.conf: |
    {allow, {username, {re, "^dashboard$"}}, subscribe, ["$SYS/#"]}.
    {allow, {ipaddr, "127.0.0.1"}, all, ["$SYS/#", "#"]}.
    {allow, {username, "zigbee2mqtt"}, all, ["zigbee2mqtt/#", "homeassistant/#", "hass/status"]}.
    {allow, {username, "home-assistant"}, all, ["zigbee2mqtt/#", "homeassistant/#", "hass/status"]}.
    {deny, all, subscribe, ["$SYS/#", {eq, "#"}, {eq, "+/#"}]}.
    {deny, all}.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: emqx-users
  namespace: emqx
spec:
  encryptedData:
    users.csv: AgBi0q3vzWZYuf14GsghJMyx9lewQUi7OShdvScM/eS5BVElYl+MK6OCbbUhxoBc2zvy1BhDdiNibxGE1+LTh87S2UiSLxu8mRQnuhUAVbjH31OtJX+0Ty82QLgUEUqZUVGbR3RfHW7IxxocugOA8EO7NtxkwpWiKesemfp3DxuEvbfssHrMOm2gvfVSATg+8dK4uhGFCeIccrz5jVRJgx/Ia3rQrGFfSHtIX2d9Mv9cUU00RDcakibB4UnvEFNyLG7r1rCZH4Ew1C9F/88RGPRi4o260yoFR166+V5zeRYYDKUQlIkl9A2AaOlnzvhidg7U80DxoQOOE3O7VkPEPhEp1NSAwRHp3TLJmFFi8toiUF22XQf1ZyzhY3Vcuy+0JCJY6LvbfTpcjdx0tSZ4Y5i8W9KKtq0ukbUvK/QP7Ut983lS2q4AyoSm3mhteZHWbt2ESFWSxKjF2+SPay4jTKJC1oxaJOfSpG2RMSXc6ZWFFWXV6yyP0zOxvrESvp9NH4S0JNSIOC+5+xyIGqhj7e/89aHVXsn1h9TQW/MjqWcf1IfQ0i4xAXTWOuQtNirZWDo3ExDHHwPYB6dHag9PJo3s3D+Tg5+zSGXR0P+UlqzrMD9yXpRDYbVNUXW+ahefZMO1Has+Tvx7SYg9OUxhbbg7WfSfz/Ez18SN+aBnEGMK09/6Xp/Pa9z+T8IKRypPJ7OirY/l1VJrEF+BYcuT4ybcOBPwC/Kl8K0OvZ/QcbLBq3vbdkq2BDOyOKHeqEnIxEoSWUoK30hwWGwh2SDpRpkQoeB4lUFUW6+l1+2IE14Rg2JLQX7k7SR85MWxMjDE0W6Kbge5YJoFGBBSWnk41g==
  template:
    metadata:
      name: emqx-users
      namespace: emqx
    type: Opaque
---
apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
  name: emqx
  namespace: emqx
spec:
  image: emqx:5.8.2
  config:
    data: |
      authentication = [
        {
          backend = built_in_database
          mechanism = password_based
          password_hash_algorithm {name = sha256, salt_position = suffix}
          user_id_type = username
          
          bootstrap_file = "/mounted/users/users.csv"
          bootstrap_type = plain
        }
      ]

      authorization {
        deny_action = ignore
        no_match = deny
        sources = [
          {
            type = file
            enable = true
            path = "/mounted/acls/acl.conf"
          }
        ]
      }

      listeners.tcp.default.enable = false
      listeners.ws.default.enable = false

      listeners.wss.default {
        bind = "0.0.0.0:8084"
        websocket.mqtt_path = "/mqtt"
        ssl_options {
          certfile = "/mounted/cert/tls.crt"
          keyfile = "/mounted/cert/tls.key"
        }      
      }

      listeners.ssl.default {
        bind = "0.0.0.0:8883"
        ssl_options {
          certfile = "/mounted/cert/tls.crt"
          keyfile = "/mounted/cert/tls.key"
          gc_after_handshake = true
          handshake_timeout = 5s
        }
      }
  coreTemplate:
    spec:
      replicas: 3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: apps.emqx.io/instance
                operator: In
                values:
                - emqx
            topologyKey: kubernetes.io/hostname
      volumeClaimTemplates:
        storageClassName: longhorn-local
        resources:
          requests:
            storage: 5Gi
        accessModes:
        - ReadWriteOnce
        persistentVolumeReclaimPolicy: Delete
      extraVolumes:
      - name: mqtt-tls
        secret:
          secretName: mqtt-tls
      - name: accounts
        secret:
          secretName: emqx-users
      - name: acls
        configMap:
          name: emqx-acls
      extraVolumeMounts:
      - name: mqtt-tls
        mountPath: /mounted/cert
      - name: accounts
        mountPath: /mounted/users
      - name: acls
        mountPath: /mounted/acls
  dashboardServiceTemplate:
    spec:
      type: ClusterIP
  listenersServiceTemplate:
    metadata:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: mqtt.vfd.ovh
    spec:
      type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emqx-dashboard
  namespace: emqx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prd
spec:
  ingressClassName: nginx
  rules:
  - host: emqx.vfd.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emqx-dashboard
            port:
              number: 18083
  tls:
  - hosts:
    - emqx.vfd.ovh
    secretName: emqx-vfd-tls
