---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_ADGUARD_PASSWORD: AgDQw+rGhdLk+8k4IG829hRvT48qCwy+1gKQQxal66305xkXGAg0zo/UI7W6E2OexTAWrgNfKx/EBfBl/5HAIf6+4/qtrynNKqTN92fUHa1m0Nw9Vk11fsibEWTgACt+NlF2k3upId92/iLh/1JhexBRHwNzAZ5/76/65TPkDkcHJsocvkziycv5hcKnkVFR6X+GSx2lTINzgxVjODF+G15HjX3pYMJFUk9KSTALlaM2q9TyCoYjpPaCKQqnnUiSWOMjZFFZrk3xxYlhmehUMmLBJRQUzaJUq0b3oMgEzeFIkrvKvO/99iDRBhf+WvlG4y0A1ZxB68gw2bS3D675nqMDr5Agmc38f0bk3o2+O63AU7VOyQ5Zd8lXHUAyNejqwuQ18cMvExYbBP82ZVpNiTWw+MV2x3yyKXlIKnDkAmBd/4T67cmVaHPtJRh26MA5bl6QdW25EJUE6FBa7douqcQ1KE8t23DeS1Aq41Bn9z6ybvuMPLyfdVFhzBg32b4IIGCfIYKGVvZXOH5xn0xGzxT1906K3ZuKsLcujb9O0eb4g2bAAspHCRECKB3ImrofqnvNKhx6JyUX+gM8sZNa0i1K9dUBY7WHsQeSepnTRhvaWNciqYMZbCtZkej8veWg1ZitOKOUk156ewHtSYFf8203m/8ZWZywPNLdfOgH+p5YdV6gcrkN1//xPV3Gu6QyaVZPNp6jh5BZc5tOW0mUJC1EdhC3KtRgu9Q=
    HOMEPAGE_VAR_ADGUARD_USERNAME: AgAgY5vCyHpOvpYTWT+KUW2N35xqwSj0HJpEF3RITA8+pW65O+diTYkXzLKoaGbfGRX/E/N/ErcYT8+skJHXquONKoTad/45j7RzUphloJUCVCz7vxHR7AJSJqcchXFriO721fwwoN+BuSikYyCRDy0rGQUoRzjv1UBeQRm3WCNtskZu3NDQc/SmDofh8QRHND8/NBU8T6QZBtgPmZIHBvGRMiPPIEN+niHuPbgwNIJmUIORMKw9Zp979B+SrAuorYIi4jCJI7WHv98QL3DXi1VELO2p+Ia4gk1JzTcXeoOcYv/CuiHSBrQGlFcYGjGYBS42QzLWCY9EtEZ2KmZpqoSJJ0jf1wO/ohEsrhLer9XUmUDSYkWv2sWzeG1VrWGkyYUSBjHbvcneMSvLmYfVlX0UoIucaUdMSrzMdNelhJAi0CUEOX5hgcP8FjHHEkLyKoiY5eqoYpkly2toyEkQTL/Zq2WXLSLxYMyrPuxTN2QJY7xbZWBMWNs8sPJSX8zUwcHVZ7HERm59REVAWTyKzfSTqC9mBCGHinE9jnmzM3BiLbor7v6Xf9WMyQxcpUt2FQ97n9vOyMct/AlqTL64MPca95PjLysPJ0hUnb86qJwqq5pxXGAnPeUtnPl1dVt7ovHgvw4XMYeH7+l58jOl9OEUHINnkEtT17MG/xUo/npmt7K2wYghGhhrZNbxQR51iNJ4K3CA7g==
    HOMEPAGE_VAR_ARGOCD_APIKEY: AgDQj780odO2lngwxHzPpSnfCEQwJ8rT9ZXBagqVs2EGuBRapon2hE1XjZSO5ErDeWmNSnkPJHucEeflxZnPaxEFnm6OQcx4w22BMSPeaFwMzQBiGRIIobdDvcs9RiVRZC4gotgbNsigzG8gQlewXZLiuJNqaI1Mpi870lGSr3WWK8i5nMNL19Bvajq5GnRnye/WFknUcW7b4P7GuPtLetClOrnVWaTABDuJkxUeWLXSQPj76usirXKl59emduaD62+qbuMWsNlk1m+4TvVelzH2F3jXSjIOPeyS8IJfpTxMc2WN9rjGNoYrPT6wimKgNBPy9CxqsMK3GEXF2Yxb2gJHFSYukHMGAJdJT1hBzvTuU+/Akn0hg7ZP4xCEjVqNZuWuCgvyq38QRuGYJ97B6Usz/BcuMPJ6lLAzF9suZDif+XxdaMVSSE1BkHh9+XJ7XzPmObSZGRLsbuwkfIVWM0p+HLjeLU4zXgBxauItARwLJTNiW6vOnQ2rILtsNF1PMajXm21K1Uz6TUiJ3a1CXudNfVL9xQAkIL8imriqtZxqoazYF5NBFESwGLg24d0oGG5xbkF+dLWMpm1ofQr3dMHpljtnjrFJffwkEw4Oga7tVyLJmUHUqefHusdhwVdJY333q80ieCHWemE7sho0pNpxu3udaUSbwX20Y/jcf+nbazX324xmwhOZMOc01eNL9CVUnoIEH/Onk44v0PSliYbtJNlhymAhBvhGgt0OndywXZRqR1o3We+qnzwlefEREoElzuZy9xAPBZuNBeaO1hSmNJ/vq+zc4fA4GZ+i/wd01JsqnckhG9if7B4TiOgjORiwQQQIl4KOFhOjHiTu+M19rmrDFcYduou1p+e+wgq2NeYDWRcKnTsYyBYl2SHrqtAGht6c/rk6SpV8ZlTlZItNboJ9y903uPY36GHUC4PebZKCS/FYDHtYCFBoFg15tgIhHtH1kJfSESZXHA79LKPXXUSx3ymybgwu+a2WrjGfo8LxnJiuBH+DMVjOKKkjga8=
    HOMEPAGE_VAR_DSM_PASSWORD: AgDeltn+Do2jG+jLwcZePEEZrAn8TXVsIOj01xSnA4mqSxZV0mySKjhbJ7hR6h2cEzi2lZoaD1DcYdNdNo+bnOBtkhWDHCcp9x7EqjVcqShtTm4XmSgUkbGRrk3t0lPy+dXdMmrtx48VEPndflon34lRbd/sbAxs7AzayLeof/tS6ke4qoTO3+I/ZfmmjbPsDbyl4qOhcjljYQyiRKs60B4CbzXhAMTgpNo42jckMFd79cbi3gNw5rksV6n/Y7EhTm5y6Ci6hHHIqhLneQe133tWxCeIG96QDY91YaATiLU/uMlVWGDufG29Ppyn5WnjSqvytUr8luIWWAAju0RT0ifGMtqBalwXi8yVXTOTeJ5e/XYdkIm7HKpDf6dXPD6g7NJEHiLiXSeq8sg+2MsvBMhDZIE5x21s/ty9Nv8kKLKbPYLcuoMFPRL+joqpUblZgkekJwEatoW3HJYtrekatLlFZRrupewP0HUu66eTWjfO+dj3ppwtpRhs1LT1IBEIGOQWvpzgM+Jr5qJlWg/tDUfFIa6VysXvSoF7UyhyQ0s5G5wDZEgcI0yUcbgua+CkJXv4WAuG+mf+ZZxQtFmm0XpUT3zB76x+65tqvrVFIuN9isSgXQfhf8P0pH7lDtAUbhpOVYiWO+cdmVfXe+TT612mHBGA0eUVHlcEE40P/yIa559ODQUfrD+W3/tU19O7eBLnEx8fY38NSoaLpi68EP1S/MhkrRXUqhpWfrbBAjY5g3fS6nzsUw==
    HOMEPAGE_VAR_DSM_USERNAME: AgBzUIlj7x6yybd3ZldpIbuyfrOfj/5zws8gl+Hb0e8PaeihQZByteX4rvKApraby9X9Dfiu2LSJ9vSTx8KF9STJBPpIy3pJoyZ4dYlYG0jfFvxrFbUHPsiYtAghZVuSgb/NflmK59Rty05y8daA6Hwxt4LJt9oOkjfG97mfzoXJBLeQR6McWFmVok61SiciyW4Gt3iWOawjFjPLh41r42DQ41eLMeBzaVWJvRujQyoDr6vjtxxyBSAcvF50psAkZ6C2HsQZOxE2Fe37kGBUZc0LuRBK3kml0ojpoQ2FFC7EGa/kDKQRCjNHGEAOwDrdza2wcrHd1b204eG8FHPIQX47YgGXq8otdrXuuT3FZdC6nF+lAY69v/ppN9oP1AaTdN4LcZGsfhc/JPwgrohDTtYNaZUrZI14sTwRCE/A7KGsHFztDEJF+2HRpr4PXWyArdlBQPAK8fFtxg4N15TKhbj12v/XmiFRCqdXE7BxMsrdbmpXnu3rTHqShfPOyLgjEtlvpe1H9VFN9m7l1oxMu8I4DT5zDwNsJO5mVTywDVYp5UQdLiiYWoQdVag+qlpgI3Yz/6I5UZuIaR7+4ryrN5Mq69bUBo+qD5atZA9uQo1s/7gE1UzQR+IavhPug2cc/cQdsRXCFJTbRT5UCEYEq4NcKfdNsaN2aagBpdUjdMhR84zNu3iYonyLW+k0RafcJf7CYzmnqAZUDQ==
    HOMEPAGE_VAR_JELLYFIN_KEY: AgBuxjdn8g58uju/ctNjJOVnykpCJKi8nKAfM13NiT91urIQqHEQG40X82uJm3LS8wau4Kcx0vtNCKnABi+Jy3A/j73pyN2wtNfer/CGzrpMuq9u10SsuhSXC+BgS6D80Y67TH6RaeMnzSDtQW+OH2MgG4AfrE4Rbh935tnI/i/XuLKc/B4jDro2fd9Oi4XAPe7QkO2oYZvR61/FK+5+FYhHtcT8Y6FHtxyafIvMM1uimF/Uo2oims54l+Qv1UjslRXggBd6nVLC/qeRe233pFhc2ro3qmHcSBfBSQ8wM8M0jn854eNF3Wsruv6sHRnra2bBdcAVlBkfEp8M8j2bT45Z78s0HcLN8JXyl0DUwVk2m+8KXxPj+Jofm5EK5yiW7uQhov6i8FsWXhPU1R9fHGEmdEzKR1C9XmQgapCCsPw6Zoy3Aaqki4bDC5ZwdZ6ul69XejV+kYQYpzHSEfHyRVknKfAZk7hsS13eCYGo7Ec0S1UvOI6Kiz96lIGj1wAIyN5bNhv0yq3SYy0Bx12mh6eKxIbqAHyP2NQ0QGrwz/0f3z3mL+7/+eRup7GPlVCaIKxVTcDChc5otfYAKsNpMcVGYgnor3Ku4bMrI4MVOb9g4rE6nFxbNHaquoC636Gx3orUgXtp+PS22Rb9LKSk/mi731C38vMBbnWZzfCMTAC1YG6HscPk3fsHOEegYeDc4CvUaqWTgMAqlmJUAfsHlT1l0ua7BopRLT3oARUygUVVTA==
    HOMEPAGE_VAR_PYLOAD_PASSWORD: AgAd4pEjgYAZBBq4Q6HOEMsMpP0tF/Ic6fLm5Z2olexHC95Lc+KmJ2uDdX2adfq2flFPfLGP7K35cYKosLZtlVo4FBfg/AUPhe2YtbJtBVhBei2fnK+LLIxnPP+sk86LmuA/mi7e0dlEV32AfTFebivBAtfYu0abaG01Nd9FlDKBrv+wf0RVJWJNAATJWCjTog78ShEmIKjZS6EsPrj2hdfp/SUOqU/g6KnFm368ofZaASusm84CyJKhQVbk4yfg9HBDUpDx/GfcCxQspUVJ9azrHzDSxR8ISTpMfIIb7vorcgpWd+fcSfMmAO7HXhmf8wFx6Sy9SkSLmUhpCCvubf0OPLxMiMofM6gB5gfmBcKHbyFsYbQyPF7fKx/ZRBF0bjFXd9KYj0V0NXK0YymTBamKa6qtHOJimzEOsQsfxwK837e7xtfqFRQAtOU9S04EsT/PK4tQP+MeG4ZHuEXhDQnIIP0jQrqjaYGQK2vEZU5JvJmFINWQaPg34le41FnCnqhEg7CEXRzI6YGyEn6A1jwbkaMzvsuatVoaq2aMg5Q4C8uyaDSazz4R+5ATsWOBPiGn6jHeEqKPDoggVPhm6M5Upn7wSbGIX3cGqyMVtAbeG1TN3MFtZd7syzuHA0UVGqJHkudcaz23kK+tkHey6Lz9UhpvxY2aFrd9XUzPLXk0OPRHqbHWTsQzV/Y1UcVMX7Q9dv1zUy1pJsFJJkrQ+ysonhJ1LS5oafE=
    HOMEPAGE_VAR_PYLOAD_USERNAME: AgBo3zTe5uEdnbXpwqvi9JxbiHCpc1oOfGzmY0ZY/Ip4oVIHFK+dY8cVl+SQ+xM2f8WPA3KcPMAUP2fEN9vj2F6cc2KkKMdayIYthw9SE4y3v9QAzO0onBz+eUHYLg6PIlM3tWvO0C1Op3w3yjAsCQO2MIVOws9ebj3mFkFhLPgoHE1zRw8YlTxPVy7gTOcifI5/eDo3VhYD0jnZjHCVXPSRB2AkUHMBpek3zuAXx8MQ+AJSm2lde81tQaHWKCwPZadkBw22fTQ4FV46oP2VU1+q8IqO8kQZTUog5PD0+ITmF7UZ8l5YV6fO4zrgnG4UYdwV2lucj/RRPig985SlZPMIUdXmP8Qu2qDHI+aHHKeMGFEaGJtpeRTpZmBx6wbkjySxHvHLwb5IHauVmgeCFUNpbQYLXaDUnK8ziOeF6mn+e/F9lLRQTGEEPs3VylVjH6nauSptR8PBD7vlKcUxqKgfify9MZODecXsHCEJYLv038dpgnZOuqeQcaoRXiJtOqWUXNAkOsiPsm2bgPPco84w3zRo1voIyXqZJxN2EZmMAYTAlRwVb5AU0zrv6VQuDzagwNBlUMl0LUUvYBEdFQ+ZlyWr2LstHzuJDXPgB4kwO6PhKa43NIjMvUbsgFp7LXrmWnkoOKA5YLz6/Gad1tnSdtl3dWFGlYivfsagAiudwEP1m+d/oK33krigL9Q2e4LnSm8mErITfA==
  template:
    metadata:
      name: homepage-secret
      namespace: homepage
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.1.0
    helm:
      valuesObject:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v1.2.0

        config:
          settings:
            iconStyle: theme
            hideVersion: true
            target: _self
            layout:
            - Services:
                header: false
                style: row
                columns: 3
            - Favoris:
                style: row
                columns: 3
            - Favoris2:
                header: false
                style: row
                columns: 3
            language: fr
            providers:
              longhorn:
                url: https://longhorn.vfd.ovh
          bookmarks:
          - Favoris:
            - Agenda:
              - icon: mdi-calendar
                href: https://calendar.google.com/calendar/u/0/r?pli=1
            - Email:
              - icon: mdi-email
                href: https://mail.google.com/mail/
            - Youtube:
              - icon: si-youtube
                href: https://youtube.com
            - Twitch:
              - icon: si-twitch
                href: https://twitch.tv
            - Cloudflare:
              - icon: si-cloudflare
                href: https://cloudflare.com
            - Github:
              - icon: si-github
                href: https://github.com
          - Favoris2:
            - Convergence:
              - icon: mdi-email
                href: https://webmel.ac-creteil.fr
            - Mon Lycée:
              - icon: si-nextcloud
                href: https://psn.monlycee.net
            - Arena:
              - icon: mdi-castle
                href: https://externet.ac-creteil.fr
            - Cyclades:
              - icon: mdi-account-school
                href: https://candidat.examens-concours.gouv.fr/cyccandidat/portal/
            - Moodle Collège Sévigné:
              - icon: si-moodle
                href: https://moodlecollegesevigne.fr/login/index.php
            - Bibliothèque Sainte-Geneviève:
              - icon: mdi-library
                href: https://bsg.univ-paris3.fr
          services:
          - Services:
            - Jellyfin:
                icon: si-jellyfin
                href: https://jellyfin.vfd.ovh
                widget:
                  type: jellyfin
                  url: https://jellyfin.vfd.ovh
                  key: '{{HOMEPAGE_VAR_JELLYFIN_KEY}}'
            - Adguard Home:
                icon: si-adguard
                href: https://ns1.vfd.ovh
                ping: 192.168.10.230
                widget:
                  type: adguard
                  url: https://ns1.vfd.ovh
                  username: '{{HOMEPAGE_VAR_ADGUARD_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}'
            - NAS:
                icon: si-synology
                href: https://nas-m.vfd.ovh
                ping: 192.168.10.251
                widget:
                  type: diskstation
                  url: https://nas-m.vfd.ovh
                  username: '{{HOMEPAGE_VAR_DSM_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_DSM_PASSWORD}}'
            - Pyload:
                icon: si-flood
                href: https://dl.vfd.ovh
                widget:
                  type: pyload
                  url: https://dl.vfd.ovh
                  username: '{{HOMEPAGE_VAR_PYLOAD_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_PYLOAD_PASSWORD}}'
            - Argo CD:
                icon: si-argo
                href: https://argocd.vfd.ovh
                widget:
                  type: argocd
                  url: https://argocd.vfd.ovh
                  key: '{{HOMEPAGE_VAR_ARGOCD_APIKEY}}'
            - Longhorn:
                icon: si-rancher
                href: https://longhorn.vfd.ovh
            - Victoria Metrics 01:
                icon: si-victoriametrics
                href: https://vm01.vfd.ovh/vmui
            - Victoria Metrics 02:
                icon: si-victoriametrics
                href: https://vm02.vfd.ovh/vmui
            - Vaultwarden:
                icon: si-bitwarden
                href: https://vaultwarden.vfd.ovh
            - EMQX:
                icon: si-mqtt
                href: https://emqx.vfd.ovh
            - Zigbee:
                icon: si-zigbee
                href: https://zigbee-m.vfd.ovh
                ping: 192.168.10.80
            - Zigbee2MQTT:
                icon: si-zigbee2mqtt
                href: https://z2m.vfd.ovh
            - Home Assistant:
                icon: si-homeassistant
                href: https://ha.vfd.ovh
            - Music Assistant:
                icon: si-applemusic
                href: https://ma.vfd.ovh
            - Node-RED:
                icon: si-node-red
                href: https://nodered.vfd.ovh
            - Grafana:
                icon: si-grafana
                href: https://grafana.vfd.ovh
            - Imprimante:
                icon: mdi-printer
                href: https://printer-m.vfd.ovh
                ping: 192.168.10.155
            - Freebox:
                icon: mdi-wan
                href: https://router.vfd.ovh
                ping: 192.168.10.254
          widgets:
          - datetime:
              locale: fr
              format:
                dateStyle: long
                timeStyle: short
          - kubernetes:
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "total"
          - longhorn:
              total: true
              expanded: true
              labels: true
              nodes: true
          - search:
              provider: google
              target: _self
              showSearchSuggestions: true
          kubernetes:
            mode: cluster

        serviceAccount:
          create: true
          name: homepage

        enableRbac: true

        envFrom:
        - secretRef:
            name: homepage-secret

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - host: home.vfd.ovh
              paths:
              - path: /
                pathType: Prefix
            tls:
            - secretName: homepage-vfd-tls
              hosts:
              - home.vfd.ovh

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
