---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: home-assistant
spec:
  instances: 2

  storage:
    storageClass: longhorn-local
    size: 20Gi

  backup:
    volumeSnapshot:
      className: longhorn-backup-vsc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: home-assistant
    repoURL: http://pajikos.github.io/home-assistant-helm-chart/
    targetRevision: 0.2.89
    helm:
      valuesObject:
        env:
        - name: PYTHONPATH
          value: /config/deps
        - name: DB_PG_URI
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: uri
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: '[ { "name": "macvlan", "namespace": "kube-system", "ips": [ "192.168.10.231" ] }]'
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                  - arm64
        persistence:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: longhorn
          size: 10Gi
        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prd
          hosts:
          - host: ha.vfd.ovh
            paths:
            - path: /
              pathType: ImplementationSpecific
          tls:
          - secretName: ha-vfd-tls
            hosts:
            - ha.vfd.ovh
        initContainers:
        - name: init-hacs
          image: bash:5.2
          command: [ "bash", "-c", "cd /config && [[ ! -d /config/custom_components/hacs ]] && wget -O - https://get.hacs.xyz | bash - || exit 0" ]
          volumeMounts:
          - mountPath: /config
            name: home-assistant
        configuration:
          enabled: true
          forceInit: true
          trusted_proxies:
          - 100.64.0.0/16
          templateConfig: |-
            default_config:

            {{- if .Values.ingress.enabled }}
            http:
              use_x_forwarded_for: true
              trusted_proxies:
                {{- range .Values.configuration.trusted_proxies }}
                - {{ . }}
                {{- end }}
            {{- end}}

            homekit:
              ip_address: 192.168.10.231
              filter:
                exclude_domains:
                  - automation
                exclude_entities:
                  - sun.sun
                  - zone.home
                  - weather.home
                  - sensor.hacs
                exclude_entity_globs:
                  - sensor.*_battery

            emulated_hue:
              type: alexa
              advertise_ip: 192.168.10.231
              listen_port: 80
              expose_by_default: true
              exposed_domains:
                - light

            recorder:
              db_url: !env_var DB_PG_URI
              purge_keep_days: 365
              exclude:
                domains:
                  - automation
                  - update
                entity_globs:
                  - sensor.sun*
                  - weather.*
                  - calendar.*
                  - sensor.aulnay_sous_bois*
                  - sensor.93*
                entities:
                  - sensor.date
                  - sensor.last_boot
                  - sun.sun

            frontend:
              themes: !include_dir_merge_named themes

            automation: !include automations.yaml
            script: !include scripts.yaml
            scene: !include scenes.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: home-assistant
