---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    HOMEPAGE_VAR_ADGUARD_PASSWORD: AgAudXhvXdDffWvqZnX85z2tjUw+BCpb4tCWnuOQSOeo84orcQOArzxlMBSz62KRKmqqUvykJ9MEU+6L3RHKnBMkhLBa27bmdQRYnF/AV0KTl7qTNU+l6frQ+uYiro3kOlzFjnWH3HErPVTOmjQYo03Hb8o3MpD/L918in652zmHD0Z8XgIEAflhSrF+YVJuW6bhB1rmu/2egoxiBFzrsTCG6SFn/865+CXDdNB/z6/SLWK6PDGTrj1uJKCTQ6cshHu1yny9gHKgNx4O617iqB0H8+/PKvjgRB2bGqCue2KxjQK4LD1N4cAs7fuJXnFVBYUPD6S7DnILIxG04F/TqhjUpWC88QOeXLSQDqyvA2tpHLgu+QJ+saw4x9yExlUohL1wUUws4w6d5QaTEWc93N14962L/mXbyrgJDbikE/2DoNDERya5DgJivJgGwhRovh66qPuohc94kz32HQdcOowfPKxL+cthlDTGiEoB2HyG0bb+5oNUMaJpGGKeJ64ksdf8OrxnLIG5H8rkf277SmFfb9n/ms2YOcNULYf3sQdGMEJ8V7yhES3JqMx8pNkZwiwnPsTPF7a3X1byDIj4xmjlgSoxojQn0hwjjJkJoq4pcSHIcYnmolOE6Q+3PKreCOjo5VfikSP/2MKBdQ+wwLEZmvra/8fHdXlgjhZF3hhihLAa+JExXb9kLdkWMfc/4ZJdpCfzvK4f2qpYc8/ELpSGQeBqERVvB5E=
    HOMEPAGE_VAR_ADGUARD_USERNAME: AgBj6h0o79E3jVTVdQVMh+3hmxw5SoCScfJ0YbRTVkB9RY83hTxhJzhNAMdWEAZZt5DQbwnRWg4FHbSpXJQg71qRWBoskGtpIAJVLQMIZkHdSSbYJI83IVq6fzvsnWHXW8DWGWDSsViogD0mDsbnJ8Yg2ivpp7eUxDYioNDXhNHd9nsNNRStKOOg/JIzd+foYuPSCFbDSW5bslLKVzwvJ6SNfgdl9XZIoICdY+Ce0XjmyIBnI84hH7z5+/fAbq15qbE2jIfFt0WN9U5naL3C7wgfagEnLrrMGmLThCbOcBjphmGRC3A7RAaT7Bj3t4l415gOGjlvhz7NWUptXL1yr2n/sKgrMTXAImDsVNYlbyGQmLb7tZdWoLWFauvSGFiFM7lm+W5cnzETjHrj7M4a3qd/FJke6010YN+XDiBcnXgkdrfMxtjc+qeadkLVgZXC6tl6OkaCCJnA64nCfF3wyfQdzaaZ2R/TTAuhpfOEYMbZFpxrP9s7TrLCMNb6QvXRVHcwBhMnBptIqYzRnbsB6rvdYSQ6BYFJ1FvkJ3105+uWCQgI7VQXi+2E8ICn9cbrJygZPRJimzEXrzUCf2eiIL5PDdzZgtO7sV4F4icz+bjapcY04a+MWa4VH6X+cM8Mg0Qi/83IBsUu0Z31OrQyjF8nZu4z89qsWY+dqQ5pz5LPIQss11U8aOzNbvlhDgOm63/mi0yxDQ==
    HOMEPAGE_VAR_DSM_PASSWORD: AgDe7ViH1+xqn63jh2U1sPVuHsE+dEjAUS7ZcKMSg4h+DNzs6THdnkd/UQhJ97gCnkw36fD5t+GrCq5bU3H7fXnHPyGNo2s/a2yce4jLhYXbCdLFbWKHGWtHeVWZVw9fVXs7KmL8kdfiY3Ujm342YXF4Hhld3TrPFNNIn8vEHAbCx1qTjNFAq8zb2n2M7yM+B3S/p5TitDTn8XD+XTGPsUX73Trtf1nsIblmUz/joKAAF5hAGAedcPALl8LXl3jFdI8UsMxfdl4UQN89Nzx9zOgvmMaDWhKCnlvyiOEgcLjVuJg5dAiEPpqcPKtU62l59OlQvZTDt6KAm2O6+2Mw0/jy8xG711p0VL9d/mJQvleCzB0kdhT30ZT53oMbvnXO0FG1c+VpmwN+k6D7o0UvaKZ498HjSNX30cyUsb2V3eq0TBtKoTlEa+Nj7UiYXMOKv4Rt/7sBxfHUqIdF80bQZbjd6Xg8XbhUcdGdg+jaoRwhSzILe/mB2Wv/1AMClsRnfme1HQFrbjyk2OpjjAWKqjx6g72Sx78QhLrqbqVNQfpkS23kGMGy1WrhJZqS7tYj1K67pNJ1qTC75pIhkziBOYDF/tfxsI6ijvxcxhRA2b7gJ1ga53Osexw04bXaOOJjH+7qc7TvuJreGAxy6UJjnjSX9Qa0bXGXr8I4gsGCKYrGxM7+M0ELjZ05fx0P7KUtIsIQz3++MwTHnD6V3HJV2yYTGerktrwZ/gzwAE3M6HtialyhlfwNxA==
    HOMEPAGE_VAR_DSM_USERNAME: AgBIwmcNMEjpKvJl2Y+6CAq8aylqM594AE3IguI+dI0nmKCv5CJia2HgwjbBrO4xBj+ILDLtUBSZOozZtSMOsABmOEQCH98w/DUYWc5wq3rGQLVmTORAtCGQf4brVXLSQ0QyB6elJo1XBkIsyi3AMjMFNgUFC3viHoba5MM9fYX04EnafCQz6y5PMQ7wmWogvANCn9ouwYPt7+zaUbiRxpVJMT+mPBrO7VhJjy+P1WQ4K+FOAxwpO7w4NXtQmMce2guz7dWcj5Z3Ph6tck4dUltHPbH1gT7dv9wI2NjcL/0F6lgQmK+gtNSF/X3clbJCgQ0LJlCqzl1HeQFZS/Fiisf9pSILoS/UxcLVaTyGv7vPUCIJEORYIGSGLx91O6qvTe0fc+ZkfizBibgL5zgeaSELeFiI2vMq00beDBynP/+LOVVj6pUfOYOkj/Yc5oCV1vWFW6+4VOE70Q7aEdrGs2nr4gKfd0oS/NTBx4D7fGqZreFt/+wcEok+nKxNcvvdl6NDSNcPiGfoYbNk4uZAu3hN+Vj8XFPWHdN1BFPiJXzUmhRY33jxWoAzjolb9pQ9e8fLgOgQSCZM/btEvXz9Eq7XrcUBvkVi8weSfcNsoK7AhSJ4kISRZEVr2IyVfoocS+8cZzo4uasqldSiTUeCFnhaN88+AT29dVmrdi46m0fQ6UyUTbN00tszy7XGlbRsAZZ1rXgLEyjFgQ==
    HOMEPAGE_VAR_JELLYFIN_KEY: AgCrnRcVzbOxSjZ3z2sI7OX2kjqocs/ZjAUNc1ZOhmFWv9CgSKW5Juv6EVBXG3ncUUcbVDd0MEji70nnTbn/s1ziz73WULxP8727kuPTMItzmI5Y+9zfUyEU8efFRxHVlQoDM2S5wBUBfDPNwlsY0nmX0BGPYV4BsD2i7fLDFxp5Vp9/haX48nXEyB5tKdal7OWAwUnWRg+U4admI8OrfhFeFlJGIIWcaQ506+l+iv1udgJcfDm+sFSH6BnXCrXFNp9SEvSRd+0FFf+PBoQfnK13igXdBz7EDshOlNLRhU+Omsjy04y2YaMrdwi58VnIA7uMaC+V4xCUi1QE/iumgS9W4dHfGknt4RjAzTKYHxe5mrfCufLj/nvX8r1dT2SRRoqG/mj4B74EWqhI+mKvMBEXkSsPPMTsiSy4kNA7o6EFwY/nl0sec23a8pL0AuXQ8slmU6p4y1T3zS7TssjinRxwiuasUJIGrHX9E+UMLKtW4EHi/J15zoZ8ApmriwzgI4iZ0f7qRUjhDa9SU1vbZGY2sFGfMD94x0U5jT3YUEp1CcI689nCYoSyRv0U5P5T5pGZnk+o+RckzuYs4yOEj9vYXks6IPq0eh/2UwXB1efoeZEg2ZznHIg/YPNUtghMhW6aHd21GCoYeTBff8deFysQYdY8ea3En3Xud5tnuL3OGasGyM4l8QnsH+E5opK+5x4h0ZNtUkxqP6hb+zT8dQXn5jXm4kt8GrQphbW8Lwmm4A==
    HOMEPAGE_VAR_PYLOAD_PASSWORD: AgCn3C9GMqdu6wyT3u5mCFEg3B0hySuSQ7g6d7S0X07QJEwtR6Kwz0Y2P70Ir0sDySzjm3nYNXOC3vu3N5G5Mx/JcXb5Q2BFvSKZSCxauEQPX/n9LUaCETdK+2/tsmamRQKX/RkurGCbY21PrT0cedtXvKWkG2m/XNXTChy9KKYFQ3cmeP2DEYGzPWmqMEh4oRv38r6o7BUZhqrpwOTXr6+kgWYUURo8p7eVm4LQonJcTWdzxvcPKGHEcX/qWeTVPkHo88UumVvTBr4vN3cz5fGQ5nnR1rx+Fj8pYkstDNPyQaoJcNaTgB+YuIbyzBLxQUSvoa/Gcvi9PI26RdhWR7PNCtv9Yeb7wIMhj8r9iKr9g9J+vK+yfiwgUmrvxlflE4g38mWe8aSNYeVhyfrrcyv6i6slIoNXKGJadncSNp8zIkIzF9GHgcNZxLWTCzcGbhWeDfCUNqZNaX8wR7DZeI5EQMH6UwuiTLTP1zZnra5ZusZUJg2wppTAlPBe+Mjj9G3N3pB0yslDafJTYivYRip2xwW0UeJwd69INVBHh8++6UKwL/oWaqXMpUlwaRU5iLaW4lHqpeJk0+ySeUH/nprIxiZTbhSa7tgA82G4gVwdiM8I4O7Pkl3Syzv9AtC66f4BaLolgWhCdXlDOvVEjdH1FSyy66o0dKlVZ7B1XmxPdV2SBg++T1B/EFyF1SFAwZVfobtl6sgHXcnrDIv5ABj6S7StYZtKga4=
    HOMEPAGE_VAR_PYLOAD_USERNAME: AgCokDiGOw5CijXKSDcjf3bmw/ibndNpZ3vLo7PxwLjv3QhYvO37g5FSfdt5+IA6aza/hgGOqKPCtabHhrVxDZkrNRnPuufH3mKOLkIZQMW61C+zroimgQQ1IQd0Mtr8takedBnlcqZFCN9dfsiy/haI6iL3dzdC3bZeM+0a2CEv74yCDNsZjMJI2YbTuTcPM1i9J/jLU+Sgk504vqxYzGS38cLxxa2gWsHJII6Mrgqw/C3UDJbPG8YHexooOJo/RGqi22GZKJK0ZXp8jrd+SG1369VoWBhA+YGuqHL30/ZK5FNpm2MaJaOpPFO3qShCBVQtErJ5orEojfdnWEryXnvlmIzxQYVZNKLNd8ImMcRIX5pSqQHiQrb3reEPDPqMYj540Ts8WF+Zk0n9orlgUngGAoLOhrPTbzTxLZSp2dmT/+McR3B7Akh+HWlOIDun8/rMAXm1fB9T4hbNgxvNDkk6CceBaImAvyJ3cHyf+SPUg3BWbfUBNeB5+Nb9UYFWYiQEF/PovBtKu+JBhJNLv9jCSOAOgJXEEiuZe6yew8P/E9Wa8bREwhPOmoRXuKYx9aqsVhTEwqdBUFBx8JGCFQCibmLZzNNtew1Vm1Uvna9s/oAuksTieNkiKCxBDqZQvDqyZFvZGpTI8tr1ADzrJe641U5Q/KzcUNbQ1p9B6RPDI1wJB0TDCd0jvwbaHi7Gs1U48u8FyIYJIA==
  template:
    metadata:
      name: homepage-secret
      namespace: homepage
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: homepage
    repoURL: https://jameswynn.github.io/helm-charts
    targetRevision: 2.0.1
    helm:
      valuesObject:
        config:
          settings:
            iconStyle: theme
            hideVersion: true
            target: _self
            layout:
            - Services:
                header: false
                style: row
                columns: 3
            - Favoris:
                style: row
                columns: 3
            - Favoris2:
                header: false
                style: row
                columns: 3
            language: fr
            providers:
              longhorn:
                url: https://longhorn.vfd.ovh
          bookmarks:
          - Favoris:
            - Agenda:
              - icon: mdi-calendar
                href: https://calendar.google.com/calendar/u/0/r?pli=1
            - Email:
              - icon: mdi-email
                href: https://mail.google.com/mail/
            - Youtube:
              - icon: si-youtube
                href: https://youtube.com
            - Twitch:
              - icon: si-twitch
                href: https://twitch.tv
            - Cloudflare:
              - icon: si-cloudflare
                href: https://cloudflare.com
            - Github:
              - icon: si-github
                href: https://github.com
          - Favoris2:
            - Convergence:
              - icon: mdi-email
                href: https://webmel.ac-creteil.fr
            - Mon Lycée:
              - icon: si-nextcloud
                href: https://psn.monlycee.net
            - Arena:
              - icon: mdi-castle
                href: https://externet.ac-creteil.fr
            - Cyclades:
              - icon: mdi-account-school
                href: https://candidat.examens-concours.gouv.fr/cyccandidat/portal/
            - Moodle Collège Sévigné:
              - icon: si-moodle
                href: https://moodlecollegesevigne.fr/login/index.php
            - Bibliothèque Sainte-Geneviève:
              - icon: mdi-library
                href: https://bsg.univ-paris3.fr
          services:
          - Services:
            - Jellyfin:
                icon: si-jellyfin
                href: https://jellyfin.vfd.ovh
                widget:
                  type: jellyfin
                  url: https://jellyfin.vfd.ovh
                  key: '{{HOMEPAGE_VAR_JELLYFIN_KEY}}'
            - Adguard Home:
                icon: si-adguard
                href: https://ns1.vfd.ovh
                ping: 192.168.10.230
                widget:
                  type: adguard
                  url: https://ns1.vfd.ovh
                  username: '{{HOMEPAGE_VAR_ADGUARD_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}'
            - NAS:
                icon: si-synology
                href: https://nas-m.vfd.ovh
                ping: 192.168.10.251
                widget:
                  type: diskstation
                  url: https://nas-m.vfd.ovh
                  username: '{{HOMEPAGE_VAR_DSM_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_DSM_PASSWORD}}'
            - Pyload:
                icon: si-flood
                href: https://dl.vfd.ovh
                widget:
                  type: pyload
                  url: https://dl.vfd.ovh
                  username: '{{HOMEPAGE_VAR_PYLOAD_USERNAME}}'
                  password: '{{HOMEPAGE_VAR_PYLOAD_PASSWORD}}'
            - Argo CD:
                icon: si-argo
                href: https://argocd.vfd.ovh
            - Longhorn:
                icon: si-rancher
                href: https://longhorn.vfd.ovh
            - Victoria Metrics 01:
                icon: si-victoriametrics
                href: https://vm01.vfd.ovh/vmui
            - Victoria Metrics 02:
                icon: si-victoriametrics
                href: https://vm02.vfd.ovh/vmui
            - Vaultwarden:
                icon: si-bitwarden
                href: https://vaultwarden.vfd.ovh
            - EMQX:
                icon: si-mqtt
                href: https://emqx.vfd.ovh
            - Zigbee:
                icon: si-zigbee
                href: https://zigbee-m.vfd.ovh
                ping: 192.168.10.80
            - Zigbee2MQTT:
                icon: si-zigbee2mqtt
                href: https://z2m.vfd.ovh
            - Home Assistant:
                icon: si-homeassistant
                href: https://ha.vfd.ovh
            - Music Assistant:
                icon: si-applemusic
                href: https://ma.vfd.ovh
            - Node-RED:
                icon: si-node-red
                href: https://nodered.vfd.ovh
            - Grafana:
                icon: si-grafana
                href: https://grafana.vfd.ovh
            - Imprimante:
                icon: mdi-printer
                href: https://printer-m.vfd.ovh
                ping: 192.168.10.155
            - Freebox:
                icon: mdi-wan
                href: https://router.vfd.ovh
                ping: 192.168.10.254
          widgets:
          - datetime:
              locale: fr
              format:
                dateStyle: long
                timeStyle: short
          - kubernetes:
              nodes:
                show: true
                cpu: true
                memory: true
                showLabel: true
              cluster:
                show: true
                cpu: true
                memory: true
                showLabel: true
                label: "total"
          - longhorn:
              total: true
              expanded: true
              labels: true
              nodes: true
          - search:
              provider: google
              target: _self
              showSearchSuggestions: true
          kubernetes:
            mode: cluster

        serviceAccount:
          create: true
          name: homepage

        enableRbac: true

        envFrom:
        - secretRef:
            name: homepage-secret

        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - host: home.vfd.ovh
              paths:
              - path: /
                pathType: Prefix
            tls:
            - secretName: homepage-vfd-tls
              hosts:
              - home.vfd.ovh

  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
