---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: music-asssitant
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: music-assistant-server
    repoURL: https://lmatfy.github.io/charts
    targetRevision: 0.1.6
    helm:
      valuesObject:
        podAnnotations:
          k8s.v1.cni.cncf.io/networks: '[ { "name": "macvlan", "namespace": "kube-system", "ips": [ "192.168.10.232" ] }]'
        image:
          repository: ghcr.io/music-assistant/server
          tag: 2.5.8
        persistence:
          data:
            enabled: true
            accessMode: ReadWriteOnce
            storageClass: longhorn
            size: 10Gi
            mountPath: /data
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - host: ma.vfd.ovh
              paths:
              - path: /
                pathType: ImplementationSpecific
            tls:
            - secretName: ma-vfd-tls
              hosts:
              - ma.vfd.ovh

  destination:
    server: "https://kubernetes.default.svc"
    namespace: music-asssitant
