---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pyload
  namespace: argocd
spec:
  project: applications

  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true

  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 3.7.3
    helm:
      valuesObject:
        controllers:
          main:
            strategy: Recreate

            containers:
              main:
                image:
                  repository: linuxserver/pyload-ng
                  tag: 0.5.0b3.dev87-ls165
                  pullPolicy: IfNotPresent

        service:
          main:
            controller: main
            ports:
              http:
                port: 8000

        ingress:
          main:
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prd
            hosts:
            - host: dl.vfd.ovh
              paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
            tls:
            - secretName: dl-vfd-tls
              hosts:
              - dl.vfd.ovh

        persistence:
          config:
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            storageClass: longhorn
            size: 5Gi
            globalMounts:
            - path: /config
          downloads:
            type: persistentVolumeClaim
            accessMode: ReadWriteOnce
            storageClass: smb-multimedia
            size: 100Gi
            globalMounts:
            - path: /downloads

  destination:
    server: "https://kubernetes.default.svc"
    namespace: pyload
