---
apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-tls
  namespace: rabbitmq
spec:
  dnsNames:
  - rabbitmq.vfd.ovh
  - rabbitmq-m.vfd.ovh
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prd
  secretName: rabbitmq-tls
  usages:
  - digital signature
  - key encipherment
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
  annotations:
    rabbitmq.com/operator-connection-uri: https://rabbitmq-m.vfd.ovh
    rabbitmq.com/topology-allowed-namespaces: "home-assistant,zigbee2mqtt"
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      mqtt.durable_queue_type = quorum
    additionalPlugins:
    - rabbitmq_mqtt
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: rabbitmq.vfd.ovh
    type: LoadBalancer
  persistence:
    storageClassName: longhorn-local
    storage: 25Gi
  tls:
    secretName: rabbitmq-tls
    disableNonTLSListeners: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - rabbitmq
        topologyKey: kubernetes.io/hostname
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-management
  namespace: rabbitmq
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: rabbitmq-m.vfd.ovh
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq
            port:
              number: 15671
  tls:
  - hosts:
    - rabbitmq-m.vfd.ovh
    secretName: rabbitmq-tls
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: mqtt-queue
  namespace: rabbitmq
spec:
  name: mqtt-queue
  vhost: "/"
  type: quorum
  durable: true
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: zigbee2mqtt-binding
  namespace: rabbitmq
spec:
  source: amq.topic
  destination: mqtt-queue
  destinationType: queue
  routingKey: "zigbee2mqtt.#"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: homeassistant-binding
  namespace: rabbitmq
spec:
  source: amq.topic
  destination: mqtt-queue
  destinationType: queue
  routingKey: "homeassistant.#"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: hass-binding
  namespace: rabbitmq
spec:
  source: amq.topic
  destination: mqtt-queue
  destinationType: queue
  routingKey: "hass.#"
  rabbitmqClusterReference:
    name: rabbitmq
