---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-credentials
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB//YP7+h9oFMppZWdQn4WbdGYKGckJ/NeZuhwKSoo7PQksSQxtGX7eOQtcbZWIPcLZDRg3dLWZifry8ghNz0FbBZaAp6n4crZzMlihO2slZhUM5eA34fGDDatU3xHJY4wn6LZm4mGzQ/NaDSDwpakWb/VpZM/WA8LeVQVpNzE7PTg1Zc4wTpmPFwiO/0+sB/UCe9dSVtoRh2exXPdRaNi2+pHBjjIP+psFn8+ZQFVAw1TpG8TVpLKnjGrUzLavCiiNvuUVhHvRmn7x2fDfGyoRtdIX5SiwN2FItaq9VE3sbUx078qwkU/5YMGNA5UFDjulyOwHTD70q2CjIQJy+TdBOaI/FOIJeAAh/NrLgRn1JkrKP1Sg6AFjJEpAtAby9GbbiKOSajSEirTGWIpKnb7dKqLfASdQRr8h7kk4btJDlP0nZv5Qex5Dm5JPTIJ1EvAjABn02qhRaPpo2lUjF+87l66xOKSTuXj2Ejh4EIEQXCAYoGv2Nu/ub/ZijrNr3NJqpYcd0WA3uhSbBo0i90fM9pvXWoUMVz7t43YaePBcLkJY1NbcEMLYNrVTq/50N84K28wmUpMs6FeSL29QHAuydop9Zw3oQdZx+KloLfcTEKnePyMLqYMcECsreXtNLZ52+k5v3LHH223ATo1FPMaOOVtyZ4I1RW/FHHJm6c0IfRawIIzmxqzquWT1IKn7O9CpTQsCcqNl+yDVeKxEs9ZW+2CP5J6DLgTCFVW6jspfBoAdpqHaXqYd
  template:
    metadata:
      name: cloudflare-credentials
      namespace: cert-manager
    type: Opaque
