---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        dns01RecursiveNameservers: "1.1.1.1:53,1.0.0.1:53"
        dns01RecursiveNameserversOnly: true