---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/longhorn
- storage_local.yaml
- cifs_credentials.yaml
- scheduled_jobs.yaml

patches:
- path: overlay.yaml
