---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        defaultSettings:
          backupTarget: cifs://192.168.10.251/Backups
          backupTargetCredentialSecret: cifs-credentials
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prd
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
          ingressClassName: traefik
          host: longhorn.vfd.ovh
          tls: true
          tlsSecret: longhorn-vfd-tls