apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: trim-fs
  namespace: longhorn-system
spec:
  cron: "0 3 * * *"
  task: "filesystem-trim"
  groups:
  - local
  - replicated
  concurrency: 3
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup
  namespace: longhorn-system
spec:
  cron: "0 4 * * *"
  task: "backup"
  groups:
  - replicated
  retain: 7
  concurrency: 3
