---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/victoria-metrics

patches:
- path: overlay.yaml
- target:
    kind: Application
    name: victoria-metrics
  patch: |-
    - op: replace
      path: /metadata/name
      value: victoria-metrics-amd
